# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ConfigWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(301, 352)
        self.gridLayout = QtWidgets.QGridLayout(Config)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Config)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Config)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.mask_path_line = QtWidgets.QLineEdit(Config)
        self.mask_path_line.setMinimumSize(QtCore.QSize(0, 30))
        self.mask_path_line.setObjectName("mask_path_line")
        self.gridLayout.addWidget(self.mask_path_line, 0, 0, 1, 2)
        self.color_random = QtWidgets.QSpinBox(Config)
        self.color_random.setMinimum(1)
        self.color_random.setMaximum(300)
        self.color_random.setProperty("value", 20)
        self.color_random.setObjectName("color_random")
        self.gridLayout.addWidget(self.color_random, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Config)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.max_word = QtWidgets.QSpinBox(Config)
        self.max_word.setMinimum(1)
        self.max_word.setMaximum(300)
        self.max_word.setProperty("value", 200)
        self.max_word.setObjectName("max_word")
        self.gridLayout.addWidget(self.max_word, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Config)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.font_btn = QtWidgets.QPushButton(Config)
        self.font_btn.setObjectName("font_btn")
        self.gridLayout.addWidget(self.font_btn, 1, 2, 1, 1)
        self.min_size = QtWidgets.QSpinBox(Config)
        self.min_size.setMinimum(1)
        self.min_size.setMaximum(300)
        self.min_size.setProperty("value", 1)
        self.min_size.setObjectName("min_size")
        self.gridLayout.addWidget(self.min_size, 6, 1, 1, 1)
        self.mask_btn = QtWidgets.QPushButton(Config)
        self.mask_btn.setObjectName("mask_btn")
        self.gridLayout.addWidget(self.mask_btn, 0, 2, 1, 1)
        self.max_size = QtWidgets.QSpinBox(Config)
        self.max_size.setMinimum(1)
        self.max_size.setMaximum(300)
        self.max_size.setProperty("value", 20)
        self.max_size.setObjectName("max_size")
        self.gridLayout.addWidget(self.max_size, 5, 1, 1, 1)
        self.font_path_line = QtWidgets.QLineEdit(Config)
        self.font_path_line.setMinimumSize(QtCore.QSize(0, 30))
        self.font_path_line.setObjectName("font_path_line")
        self.gridLayout.addWidget(self.font_path_line, 1, 0, 1, 2)
        self.color_btn = QtWidgets.QPushButton(Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_btn.sizePolicy().hasHeightForWidth())
        self.color_btn.setSizePolicy(sizePolicy)
        self.color_btn.setMinimumSize(QtCore.QSize(35, 35))
        self.color_btn.setBaseSize(QtCore.QSize(35, 35))
        self.color_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.color_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.color_btn.setAutoFillBackground(False)
        self.color_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color_btn.setText("")
        self.color_btn.setObjectName("color_btn")
        self.gridLayout.addWidget(self.color_btn, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(Config)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.set_btn = QtWidgets.QPushButton(Config)
        self.set_btn.setObjectName("set_btn")
        self.gridLayout.addWidget(self.set_btn, 7, 0, 1, 3)

        self.retranslateUi(Config)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        _translate = QtCore.QCoreApplication.translate
        Config.setWindowTitle(_translate("Config", "调整参数"))
        self.label_3.setText(_translate("Config", "最小字号:"))
        self.label_4.setText(_translate("Config", "背景色:"))
        self.mask_path_line.setText(_translate("Config", "source/default_mask.jpg"))
        self.label_5.setText(_translate("Config", "最大字数:"))
        self.label_2.setText(_translate("Config", "最大字号:"))
        self.font_btn.setText(_translate("Config", "字体路径"))
        self.mask_btn.setText(_translate("Config", "mask路径"))
        self.font_path_line.setText(_translate("Config", "source/default.ttf"))
        self.label.setText(_translate("Config", "颜色种类:"))
        self.set_btn.setText(_translate("Config", "配置完成"))

